name: Build LaTeX Resume

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Cache TeX Live and fonts
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            /usr/share/texlive
            /usr/share/fonts
            /var/cache/apt
            ~/.cache/fontconfig
          key: texlive-fonts-${{ hashFiles('.github/workflows/build.yml') }}
          restore-keys: |
            texlive-fonts-

      - name: Install TeX Live and fonts
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            texlive-full \
            fontconfig \
            fonts-noto-cjk \
            fonts-wqy-microhei \
            fonts-wqy-zenhei

      - name: Configure Font Substitution
        run: |
          # Create fontconfig configuration directory if it doesn't exist
          mkdir -p ~/.config/fontconfig
          # Create local.conf for font substitution
          cat << EOF > ~/.config/fontconfig/local.conf
          <?xml version='1.0'?>
          <!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
          <fontconfig>
            <!-- English Font Substitution -->
            <match target="pattern">
              <test qual="any" name="family"><string>Helvetica Neue</string></test>
              <edit name="family" mode="assign" binding="same"><string>TeX Gyre Heros</string></edit>
            </match>
            <match target="pattern">
              <test qual="any" name="family"><string>Helvetica Neue Light</string></test>
              <edit name="family" mode="assign" binding="same"><string>TeX Gyre Heros</string></edit>
            </match>
            <!-- Add more substitutions if needed -->
          </fontconfig>
          EOF
          # Update font cache
          fc-cache -fv

      - name: Create output directory
        run: mkdir -p docs

      - name: Build Resume PDFs
        run: bash scripts/build.sh

      - name: Upload PDF Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Resume-PDFs
          path: |
            docs/resume.pdf
            docs/resume-cn.pdf 