name: Build LaTeX Resume

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Cache TeX Live and fonts
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            /usr/share/texlive
            /usr/share/fonts
            /var/cache/apt
            ~/.cache/fontconfig
          key: texlive-fonts-${{ hashFiles('.github/workflows/build.yml') }}
          restore-keys: |
            texlive-fonts-

      - name: Install TeX Live and fonts
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            texlive-full \
            fontconfig \
            fonts-noto-cjk \
            fonts-wqy-microhei \
            fonts-wqy-zenhei

      - name: Configure Font Substitution
        run: |
          # Create fontconfig configuration directory if it doesn't exist
          mkdir -p ~/.config/fontconfig
          # Create local.conf for font substitution
          cat << EOF > ~/.config/fontconfig/local.conf
          <?xml version='1.0'?>
          <!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
          <fontconfig>
            <!-- English Font Substitution -->
            <match target="pattern">
              <test qual="any" name="family"><string>Helvetica Neue</string></test>
              <edit name="family" mode="assign" binding="same"><string>TeX Gyre Heros</string></edit>
            </match>
            <match target="pattern">
              <test qual="any" name="family"><string>Helvetica Neue Light</string></test>
              <edit name="family" mode="assign" binding="same"><string>TeX Gyre Heros</string></edit>
            </match>
            <!-- Add more substitutions if needed -->
          </fontconfig>
          EOF
          # Update font cache
          fc-cache -fv

      - name: Create output directory
        run: mkdir -p docs

      - name: Build Resume PDFs
        run: bash scripts/build.sh

      # Keep the artifact uploads for CI/CD purposes
      - name: Upload English Resume PDF as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Resume-EN
          path: docs/resume.pdf
          
      - name: Upload Chinese Resume PDF as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Resume-CN
          path: docs/resume-cn.pdf
          
      # Setup GitHub Pages
      - name: Setup GitHub Pages
        id: pages
        uses: actions/configure-pages@v3
        
      # Upload to GitHub Pages
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs
          
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        
      # Add direct links to the PDFs in the job summary  
      - name: Add PDF links to job summary
        run: |
          echo "### 📄 Resume PDFs" >> $GITHUB_STEP_SUMMARY
          echo "* [English Resume](https://${{ github.repository_owner }}.github.io/$(echo ${{ github.repository }} | cut -d'/' -f2)/resume.pdf)" >> $GITHUB_STEP_SUMMARY
          echo "* [Chinese Resume](https://${{ github.repository_owner }}.github.io/$(echo ${{ github.repository }} | cut -d'/' -f2)/resume-cn.pdf)" >> $GITHUB_STEP_SUMMARY 