name: Build LaTeX Resume

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends texlive-full fontconfig

      - name: Configure Font Substitution (Helvetica Neue -> TeX Gyre Heros)
        run: |
          # Create fontconfig configuration directory if it doesn't exist
          mkdir -p ~/.config/fontconfig
          # Create local.conf for font substitution
          cat << EOF > ~/.config/fontconfig/local.conf
          <?xml version='1.0'?>
          <!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
          <fontconfig>
            <match target="pattern">
              <test qual="any" name="family"><string>Helvetica Neue</string></test>
              <edit name="family" mode="assign" binding="same"><string>TeX Gyre Heros</string></edit>
            </match>
            <match target="pattern">
              <test qual="any" name="family"><string>Helvetica Neue Light</string></test>
              <edit name="family" mode="assign" binding="same"><string>TeX Gyre Heros</string></edit>
            </match>
            <!-- Add more substitutions if needed -->
          </fontconfig>
          EOF
          # Update font cache
          fc-cache -fv

      - name: Create output directory
        run: mkdir -p docs

      - name: Build Resume PDFs
        run: bash scripts/build.sh

      - name: Upload PDF Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Resume-PDFs
          path: |
            docs/resume.pdf
            docs/resume-cn.pdf 