name: Build LaTeX Resume

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Create output directory
        run: mkdir -p docs

      - name: Compile Chinese Resume
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex
          working_directory: OpenFonts.Chinese
          latexmk_use_xelatex: true
          extra_system_packages: "texlive-fonts-extra"

      - name: Move Chinese Resume to docs
        run: mv OpenFonts.Chinese/resume.pdf docs/resume-cn.pdf

      - name: Compile English Resume
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex
          working_directory: OpenFonts
          latexmk_use_xelatex: true

      - name: Move English Resume to docs
        run: mv OpenFonts/resume.pdf docs/resume.pdf

      - name: Upload PDF Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Resume-PDFs
          path: |
            docs/resume.pdf
            docs/resume-cn.pdf 